# Test profile — H2 in-memory
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
quarkus.datasource.username=sa
quarkus.datasource.password=

# Schema managed by Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create

# Disable JWT in tests
quarkus.smallrye-jwt.enabled=false
mp.jwt.verify.publickey.location=
quarkus.rest-client.permission-api.url=http://localhost:0
