# Dev profile — external APIs mocked via Microcks
quarkus.rest-client.permission-api.url=http://localhost:8585/rest/Permission+API/0.1.0
quarkus.rest-client.idfc-bank-api.url=http://localhost:8585/rest/IDFC+Bank+API/0.1.0
quarkus.rest-client.hdfc-bank-api.url=http://localhost:8585/rest/HDFC+Bank+API/0.1.0
quarkus.rest-client.lms-api.url=http://localhost:8585/rest/LMS+API/0.1.0
