-- Applicant module — initial schema.
-- Columns are snake_case (matches CamelCaseToUnderscoresNamingStrategy); TIMESTAMPTZ for time.
CREATE TABLE applicant (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    status     VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ  NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_applicant_email UNIQUE (email)
);
