-- Drawdown + payment modules and the payment outbox.

CREATE TABLE drawdown (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT        NOT NULL,
    anchor_code  VARCHAR(255)  NOT NULL,
    amount       NUMERIC(15,2) NOT NULL,
    status       VARCHAR(255)  NOT NULL DEFAULT 'PENDING',
    created_at   TIMESTAMPTZ   NOT NULL,
    updated_at   TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_drawdown_applicant FOREIGN KEY (applicant_id) REFERENCES applicant (id)
);

CREATE TABLE payment (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drawdown_id    BIGINT        NOT NULL,
    bank           VARCHAR(255)  NOT NULL,
    transfer_mode  VARCHAR(255)  NOT NULL,
    amount         NUMERIC(15,2) NOT NULL,
    status         VARCHAR(255)  NOT NULL DEFAULT 'INITIATED',
    bank_reference VARCHAR(255),
    created_at     TIMESTAMPTZ   NOT NULL,
    updated_at     TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uq_payment_drawdown UNIQUE (drawdown_id),
    CONSTRAINT fk_payment_drawdown FOREIGN KEY (drawdown_id) REFERENCES drawdown (id)
);
CREATE INDEX idx_payment_status ON payment (status);

CREATE TABLE outbox_event (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id   BIGINT       NOT NULL,
    event_type     VARCHAR(255) NOT NULL,
    payload        TEXT,
    status         VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);
CREATE INDEX idx_outbox_status_type ON outbox_event (status, event_type);
